### ISSUE TITLE
Problem with subscriptions

### ISSUE THREAD

**Issue by mariaramos08** [astone2014/devicewise-angular#2]
Hi! I have a problem with subscription, when I subscript a variable 
The following errors appear in the console:
![image](https://user-images.githubusercontent.com/48524410/56744726-a8d9f380-673e-11e9-83f9-946fa981a31e.png)
![image](https://user-images.githubusercontent.com/48524410/56744777-bd1df080-673e-11e9-8e64-bd464e3e0b5d.png)
Sometimes these errors are so many that the page is slow or is blocked and subscriptions didn't work.

**Comment by astone2014** [comment]
@mariaramos08 Can you please send me a code of the subscribe so I can recreate the issue? I believe I've pushed a change that will fix this but I don't have a test case.

**Comment by mariaramos08** [comment]
@astone2014 my issue was repeat the function getNotifications();  
The issue was resolved :)
